---
title: "Untitled"
author: "Depeng Kong"
date: "10/9/2020"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

<!-- This R Markdown document is made interactive using Shiny. Unlike the more traditional workflow of creating static reports, you can now create documents that allow your readers to change the assumptions underlying your analysis and see the results immediately.  -->

<!-- To learn more, see [Interactive Documents](http://rmarkdown.rstudio.com/authoring_shiny.html). -->

<!-- ## Inputs and Outputs -->

<!-- You can embed Shiny inputs and outputs in your document. Outputs are automatically updated whenever inputs change.  This demonstrates how a standard R plot can be made interactive by wrapping it in the Shiny `renderPlot` function. The `selectInput` and `sliderInput` functions create the input widgets used to drive the plot. -->

<!-- ```{r eruptions, echo=FALSE} -->
<!-- inputPanel( -->
<!--   selectInput("n_breaks", label = "Number of bins:", -->
<!--               choices = c(10, 20, 35, 50), selected = 20), -->

<!--   sliderInput("bw_adjust", label = "Bandwidth adjustment:", -->
<!--               min = 0.2, max = 2, value = 1, step = 0.2) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   hist(faithful$eruptions, probability = TRUE, breaks = as.numeric(input$n_breaks), -->
<!--        xlab = "Duration (minutes)", main = "Geyser eruption duration") -->

<!--   dens <- density(faithful$eruptions, adjust = input$bw_adjust) -->
<!--   lines(dens, col = "blue") -->
<!-- }) -->
<!-- ``` -->

<!-- ## Embedded Application -->

<!-- It's also possible to embed an entire Shiny application within an R Markdown document using the `shinyAppDir` function. This example embeds a Shiny application located in another directory: -->

<!-- ```{r tabsets, echo=FALSE} -->
<!-- shinyAppDir( -->
<!--   system.file("examples/06_tabsets", package = "shiny"), -->
<!--   options = list( -->
<!--     width = "100%", height = 550 -->
<!--   ) -->
<!-- ) -->
<!-- ``` -->

<!-- Note the use of the `height` parameter to determine how much vertical space the embedded application should occupy. -->

<!-- You can also use the `shinyApp` function to define an application inline rather then in an external directory. -->

<!-- In all of R code chunks above the `echo = FALSE` attribute is used. This is to prevent the R code within the chunk from rendering in the document alongside the Shiny components. -->

## new section

```{r}
if (!require("cli")) install.packages("cli")
if (!require("DT")) install.packages('DT')
if (!require("dtplyr")) install.packages('dtplyr')
if (!require("lubridate")) install.packages('lubridate')
if (!require("ggmap")) install.packages('ggmap')
if (!require("choroplethrZip")) {
  # install.packages("devtools")
  library(devtools)
  install_github('arilamstein/choroplethrZip@v1.5.0')}

library(dtplyr)
library(dplyr)
library(DT)
library(lubridate)


if (!require("choroplethr")) install.packages("choroplethr")
if (!require("devtools")) install.packages("devtools")

library(devtools)

if (!require("choroplethrZip")) 
  devtools::install_github('arilamstein/choroplethrZip@v1.5.0')

if (!require("ggplot2")) devtools::install_github("hadley/ggplot2")
if (!require("ggmap")) devtools::install_github("dkahle/ggmap")




library(readr); library(tidyverse)
sov <- read_csv("../data/Social_Distancing__Parks_Crowds_Data.csv")

dpr <- read_csv("../data/DPR_Parks_001.csv")

sov2 = sov %>%
  mutate(park_area_id = sub("\\-.*","",park_area_id))

new <- left_join(sov2,dpr,by=c("park_area_id"="facility__Prop_ID")) %>%
  select(-xmlns)
# 



library(ggmap)

register_google(key = "AIzaSyC24PcDuxFsTlP0t1lrLPRrvD7uRq98bqk")

imap = new %>% select(park_area_id, facility__Name, facility__Location, facility__Zip) %>% 
  unique() %>%
  mutate(ADDRESS_Ext = paste(facility__Name, "New York, NY", facility__Zip, sep = ",")) %>%
  mutate_geocode(ADDRESS_Ext) %>%
  mutate(district = ifelse(substr(park_area_id,1,1)=="X", "Bronx",
                     ifelse(substr(park_area_id,1,1)=="B", "Brooklyn",
                      ifelse(substr(park_area_id,1,1)=="M", "Manhattan",
                       ifelse(substr(park_area_id,1,1)=="Q", "Queens",
                        ifelse(substr(park_area_id,1,1)=="R","Staten Island","NA")
                       )
                      )
                     )
                    )
         )

write.csv(imap, file = "../output/imap.csv")




```


<!-- ```{r} -->
<!-- inputPanel( -->
<!--   selectInput("district", label = "Select district among New York City", -->
<!--               choices = c("Brooklyn", -->
<!--                           "Manhattan", -->
<!--                           "Queens", -->
<!--                           "Staten Island", -->
<!--                           "Bronx"), selected = "Manhattan"), -->

<!--   sliderInput("zoom", label = "Select map zoom level", -->
<!--               min = 5, max = 18, value = 12, step = 1) -->
<!-- ) -->

<!-- renderPlot({ -->
<!--   ggmap(get_map(input$district, source = "google", -->
<!--                 maptype = "hybrid", -->
<!--                 zoom = input$zoom, color = "color"))+ -->
<!--     geom_point(data = imap2 %>% filter(district == input$district), -->
<!--                aes(x=lon, y=lat), color = "red") -->
<!-- }) -->

<!-- ``` -->

